# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sale_records_pb2 as sale__records__pb2


class SalesRecordStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingSalesRecords = channel.unary_unary(
                '/SalesRecord/PingSalesRecords',
                request_serializer=sale__records__pb2.EmptyMessage.SerializeToString,
                response_deserializer=sale__records__pb2.PingSalesRecordsResponse.FromString,
                )


class SalesRecordServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingSalesRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesRecordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingSalesRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.PingSalesRecords,
                    request_deserializer=sale__records__pb2.EmptyMessage.FromString,
                    response_serializer=sale__records__pb2.PingSalesRecordsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SalesRecord', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SalesRecord(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingSalesRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SalesRecord/PingSalesRecords',
            sale__records__pb2.EmptyMessage.SerializeToString,
            sale__records__pb2.PingSalesRecordsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
